import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import cors from "cors";

const PORT = 3000;
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

async function startServer() {
  const app = express();
  
  app.use(express.json());
  app.use(cors());

  // AI Fallback API Route
  app.post("/api/diagnose-fallback", async (req, res) => {
    try {
      const { crop, answers, customAnswers, scores, summary, additionalInfo } = req.body;

      if (!process.env.GEMINI_API_KEY) {
        return res.status(500).json({ error: "Gemini API key is not configured on the server." });
      }

      const prompt = `You are an agricultural specialist. 
Analyze the following questionnaire responses for a crop diagnosis.
Crop: ${crop}
Scores generated by rule engine: ${JSON.stringify(scores)}
Selected Symptoms/Answers: ${JSON.stringify(answers)}
Custom Answers provided by user: ${JSON.stringify(customAnswers)}
Summary of questionnaire: ${summary}
Additional Info from Farmer: ${additionalInfo || 'None provided'}

When providing your diagnosis in the treatment or prevention steps, you MUST follow these specific rules:
- If pesticides are needed, clearly refer to the specific pesticide name.
- If medicine/chemical treatment is needed, specify the exact medicine name, how much to give (dosage), and when to give it (timing).
- If fertilizers are needed, clearly state how much to give (amount) and how to apply it (method).

Provide a comprehensive diagnosis. Do not output markdown code blocks. Output pure JSON matching this exact structure:
{
  "disease": "Most likely disease name (English & Bengali combined, e.g., 'Rice Blast | ব্লাস্ট')",
  "confidence": <number between 0 and 100>,
  "explanation": "Detailed explanation of why this disease was chosen, combining clues from the answers...",
  "treatment": [ "Treatment step 1", "Treatment step 2" ],
  "prevention": [ "Prevention step 1", "Prevention step 2" ],
  "urgency": "Low, Medium, or High"
}

Respond ONLY with the JSON object. ALL TEXT (explanation, treatment, prevention) MUST BE BILINGUAL (English first, followed by Bengali in the same string or separated by ' | ' or newlines depending on context). Example for treatment step: "Apply fungicide X (ছত্রাকনাশক এক্স প্রয়োগ করুন)"`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response from AI model.");
      }

      const diagnosis = JSON.parse(responseText);
      return res.json(diagnosis);
    } catch (error: any) {
      console.warn("Error generating diagnosis fallback:", error?.message || error);
      return res.status(500).json({ 
        error: "Failed to generate diagnosis using AI fallback.",
        details: error?.message || "Unknown error"
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*all', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
